=== dhanunjay04/tl1/tl1Capture/tl1Inventory.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT tl1-profile (map|point-type|command|command-set)+>
<!ATTLIST tl1-profile
    id CDATA #REQUIRED
    version CDATA #IMPLIED
  >
  
<!ELEMENT map (entry|default|property)*>
<!ATTLIST map
    name CDATA #IMPLIED
  >
  
<!ELEMENT entry EMPTY>
<!ATTLIST entry
    tl1 CDATA #REQUIRED
    model CDATA #REQUIRED
  >
  
<!ELEMENT default EMPTY>
<!ATTLIST default
    model CDATA #REQUIRED
  >
  
<!ELEMENT point-type (#PCDATA)>
<!ATTLIST point-type
    name CDATA #REQUIRED
    typeid CDATA #IMPLIED
    inventory CDATA #IMPLIED
    type-template CDATA #IMPLIED
    pm-template CDATA #IMPLIED
    parent-type CDATA #IMPLIED
    regex (true|false) #IMPLIED
    typename (true|false) #IMPLIED
    
  >
  
<!ELEMENT command (parameter|instances|response|type|position-block|name-block|point-types)*>
<!ATTLIST command
    name CDATA #REQUIRED
    required CDATA #IMPLIED
  >
  
<!ELEMENT point-types (type)*>
  
  
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
    name CDATA #REQUIRED
    value CDATA #IMPLIED
    property CDATA #IMPLIED
    type CDATA #IMPLIED
  >
  
<!ELEMENT instances (instance)+>
<!ELEMENT instance EMPTY>
<!ATTLIST instance
    name CDATA #REQUIRED
  >
  
<!ELEMENT response (position-block|name-block|explicit|map|example)+>
<!ATTLIST response
    object CDATA #REQUIRED
  >
  
<!ELEMENT position-block (position)*>
<!ELEMENT position (property|map-property)*>
<!ATTLIST position
    index CDATA #REQUIRED
    property CDATA #IMPLIED
    default CDATA #IMPLIED
    instance CDATA #IMPLIED
    dateFormat CDATA #IMPLIED
    timeZone CDATA #IMPLIED
  >
<!ELEMENT property EMPTY>
<!ATTLIST property
    name CDATA #REQUIRED
    map CDATA #IMPLIED
    value CDATA #IMPLIED
    default CDATA #IMPLIED
  >
  
<!ELEMENT map-property EMPTY>
<!ATTLIST map-property
    name CDATA #REQUIRED
    default CDATA #IMPLIED
  >
  
<!ELEMENT name-block (name)*>
<!ELEMENT name (property|EMPTY)*>
<!ATTLIST name
    name CDATA #REQUIRED
    property CDATA #IMPLIED
    map CDATA #IMPLIED
    default CDATA #IMPLIED
    instance CDATA #IMPLIED
  >
  
<!ELEMENT explicit (property)+>
<!ELEMENT example (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT command-set (command|inventory-override)*>
<!ATTLIST command-set
    name CDATA #REQUIRED>
<!ELEMENT inventory-override EMPTY>
<!ATTLIST inventory-override
    class CDATA #REQUIRED
    sequence (postamble|preamble) #REQUIRED
  >

=== dhanunjay04/tl1/tl1Capture/fujitsu-flashwave-4100es.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tl1-profile PUBLIC "tl1/inventory/tl1Inventory.dtd" "tl1Inventory.dtd">
<tl1-profile id="fujitsu-flashwave-4100es">
   
   <!-- ==================================================================== -->   
   <!-- mappings -->
   <!-- ==================================================================== -->   
   <map name="InterfaceSpeed">
   </map>
   <!-- ==================================================================== -->   
   <!-- Profile FW4100ES and FW4100 are indentical and should be consilidated  -->
   <!-- point types -->
   <!-- ==================================================================== -->   
   <point-type name="OSSI" inventory="true" type-template="FLT" >
   </point-type>
   <point-type name="SDCC" inventory="true" type-template="FLT" >
   </point-type>
   <point-type name="EQPT" inventory="true" type-template="FLT/Binned-PM" pm-template="optical-power-tl1"/>
   <point-type name="OC3"   inventory="true" type-template="FLT/Binned-PM" pm-template="sonet-optical-facility-tl1"/>
   <point-type name="OC12"  inventory="true" type-template="FLT/Binned-PM" pm-template="sonet-optical-facility-tl1"/>
   <point-type name="OC48"  inventory="true" type-template="FLT/Binned-PM" pm-template="sonet-optical-facility-tl1"/>
   <point-type name="OC192" inventory="true" type-template="FLT/Binned-PM" pm-template="sonet-optical-facility-tl1"/>
   <point-type name="STS1"   inventory="true" type-template="FLT/Binned-PM" pm-template="sts-facility-tl1" parent-type="STS3,OC1,OC3,OC12,OC48,OC192" />
   <point-type name="STS12C" inventory="true" type-template="FLT/Binned-PM" pm-template="sts-facility-tl1" parent-type="OC12c,OC48,OC192"  />
   <point-type name="STS3C"  inventory="true" type-template="FLT/Binned-PM" pm-template="sts-facility-tl1" parent-type="OC3c,OC12,OC48,OC192"  />
   <point-type name="STS48C" inventory="true" type-template="FLT/Binned-PM" pm-template="sts-facility-tl1" parent-type="OC48c,OC192"  />
   <point-type name="T1" inventory="true" type-template="FLT/Binned-PM" pm-template="t-carrier-tl1" />
   <point-type name="T3" inventory="true" type-template="FLT/Binned-PM" pm-template="t-carrier-tl1" />
   <point-type name="VT1" inventory="true" type-template="FLT/Binned-PM" pm-template="sonet-vt-path-tl1" />
   <point-type name="T1CLK" inventory="true" type-template="FLT/Binned-PM" pm-template="t1-clock-tl1" />
   <point-type name="ETHERLAN" inventory="true" type-template="Ethernet FLT/Binned-PM" pm-template="etherlan-tl1" />
   <point-type name="EPORT" inventory="true" type-template="Ethernet FLT/Binned-PM" pm-template="ethernet-tl1" />
   <point-type name="ETH"   inventory="true" type-template="Ethernet FLT/Binned-PM" pm-template="fujitsu-flashwave-4100es-ethernet-tl1" />
   <point-type name="RPRPORT" inventory="true" type-template="FLT" >
   </point-type>
<!--	   Newly added		 -->
   <point-type name="EPBPFL" inventory="true" type-template="FLT" />
   <point-type name="IBWPFL" inventory="true" type-template="FLT" />
   <point-type name="IPBPFL" inventory="true" type-template="FLT" />
   <point-type name="FP-MBR" inventory="true" type-template="FLT" />
   <point-type name="LAGPORT" inventory="true" type-template="FLT/PM" pm-template="fujitsu-fw-4100-LAGPORT-tl1"/>
   <point-type name="MEG" inventory="true" type-template="FLT"/>
   <point-type name="MEP" inventory="true" type-template="FLT/PM" pm-template="fujitsu-fw-4100-MEP-tl1"/>
   <point-type name="MIP" inventory="true" type-template="FLT" />
   <point-type name="MVLAN" inventory="true" type-template="FLT" />
   <point-type name="TSG" inventory="true" type-template="FLT" />
   <point-type name="FOSPORT" inventory="true" type-template="FLT/PM" pm-template="fujitsu-fw-4100-FOSPORT-tl1"/>
   <point-type name="SYNC" inventory="true" type-template="FLT"/>
   <point-type name="SYNCLIST" inventory="true" type-template="FLT"/>
	
	
<!--	close			-->
   <point-type name="RPRSPAN" inventory="true" type-template="FLT" >
   </point-type>
   <point-type name="EC1" inventory="true" type-template="FLT/Binned-PM" pm-template="fujitsu-flashwave-EC1-tl1" />
   <point-type name="FACLINK" inventory="true" type-template="FLT" >
   </point-type>
   <point-type name="LAG" inventory="true" type-template="FLT/Binned-PM" pm-template="fujitsu-fw-4100-LAG-tl1">
   </point-type>
   <point-type name="LIF" typeid="2002" inventory="true" type-template="Ethernet FLT/Binned-PM" pm-template="fujitsu-lif-tl1" />
   <point-type name="FP" inventory="true" type-template="FLT/Binned-PM" pm-template="fujitsu-fp-tl1" />
   <point-type name="Flow Point" typeid="2001" inventory="true" type-template="FLT/PM" pm-template="fujitsu-fp-tl1" />
   <!-- default -->
   <point-type name="DEFAULT" inventory="true" type-template="FLT" >
   </point-type>
   <!-- ==================================================================== -->
   <!-- command definitions -->
   <!-- ==================================================================== -->
   <command name="RTRV-EQPT">
      <parameter name="commandCode" value="RTRV-EQPT"/>
      <parameter name="tid" property="name"/>
      <parameter name="aid" value="ALL"/>
      
      <response object="centina.sa.model.service.EndPoint">
         <position-block>
            <position index="0">
               <property name="sourceId"/>
               <map-property name="aidVal"/> 
            </position>
         </position-block>
         <position-block>
            <position index="0">
               <property name="sourceType"/>
               <property name="sourceTypeId"/>
            </position>
         </position-block>
         <name-block>
            <name name="TYPE" property="description"/>
         </name-block>
         <position-block>
            <position index="0">
               <property name="operationalStateName"/>
            </position>
         </position-block>
         <explicit>
            <property name="sourceType" value="EQPT"/>
            <property name="sourceTypeId" value="EQPT"/>
         </explicit>
         <map> 
            <property name="sourceName" value="EQPT:$aidVal$"/> 
         </map>  
         <example><![CDATA["SLOT-12:DS1,EQUIP,,ACT:PROTID=SLOT-13,PRTYPE=1-1,RVRTV=Y,RVTM=8.5,TYPE=OC3241X,TRANSMODE=SONET,RETIME=Y,SHELFROLE=NC:OOS-AU,AINS&UEQ"]]></example>
      </response>
   </command>
   <command name="RTRV-OSSI">
      <parameter name="commandCode" value="RTRV-OSSI"/>
      <parameter name="tid" property="name"/>
      <parameter name="aid" value="ALL"/>
      
      <response object="centina.sa.model.service.EndPoint">
         <position-block>
            <position index="0">
               <property name="sourceId"/>
               <map-property name="aidVal"/> 
            </position>
         </position-block>
         <position-block>
            <position index="0">
               <property name="sourceType"/>
               <property name="sourceTypeId"/>
            </position>
         </position-block>
         <position-block>
            <position index="0">
               <property name="descritpion"/>
            </position>
         </position-block>
         <position-block>
            <position index="0">
				<property name="operationalStateName"/>
				<map-property name="PST" default=""/>
            </position>
             <position index="1" >
				<property name="operationalStateName"/>
				<map-property name="SST" default=""/>
            </position>
         </position-block>
         <explicit>
            <property name="sourceType" value="OSSI"/>
            <property name="sourceTypeId" value="OSSI"/>
         </explicit>
         <map> 
            <property name="sourceName" value="OSSI:$aidVal$"/>
            <property name="operationalStateName" value="$PST$,$SST$"/> 
         </map>  
         <example><![CDATA["1-T1-OSSI,T1::RPRPORT=10:926:31:OOS-AU FLT,AINS"]]></example>
      </response>
   </command>
   <command name="RTRV-SDCC">
      <parameter name="commandCode" value="RTRV-SDCC"/>
      <parameter name="tid" property="name"/>
      <parameter name="aid" value="ALL"/>
      
      <response object="centina.sa.model.service.EndPoint">
         <position-block>
            <position index="0">
               <property name="sourceId"/>
               <map-property name="aidVal"/> 
            </position>
         </position-block>
         <position-block>
         </position-block>
         <name-block>
            <name name="L2CR" property="description"/>
         </name-block>
         <position-block>
            <position index="0">
               <property name="operationalStateName"/>
            </position>
         </position-block>
         <explicit>
            <property name="sourceType" value="SDCC"/>
            <property name="sourceTypeId" value="SDCC"/>
         </explicit>
         <map> 
            <property name="sourceName" value="SDCC:$aidVal$"/> 
         </map>  
         <example><![CDATA["1-T1-SDCC,T1::L2CR=10:926:31:OOS-AU FLT,AINS"]]></example>
      </response>
   </command>
   <command name="RTRV-OC3">
      <parameter name="commandCode" value="RTRV-OC3"/>
      <parameter name="tid" property="name"/>
      <parameter name="aid" value="ALL"/>
      
      <response object="centina.sa.model.service.EndPoint">
         <position-block>
            <position index="0">
               <property name="sourceId"/>
               <map-property name="aidVal"/> 
            </position>
         </position-block>
         <position-block>
         </position-block>
         <name-block>
            <name name="CKTID" property="description"/>
         </name-block>
         <position-block>
            <position index="0">
				<property name="operationalStateName"/>
				<map-property name="PST" default=""/>
            </position>
             <position index="1" >
				<property name="operationalStateName"/>
				<map-property name="SST" default=""/>
            </position>
